package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Curso;
import java.util.List;
import java.sql.*;

public class CursoRepositoryDB implements CursoRepository{

    private final String url;
    private final String user;
    private final String pass;

    public CursoRepositoryDB(String url, String user, String pass) {
        this.url = url;
        this.user = user;
        this.pass = pass;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, pass);
    }

    @Override
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS cursos (
                id INT GENERATED BY DEFAULTS AS IDENTITY PRIMARY KEY,
                activo BOOLEAN DEFAULTS 1,
                nombre VARCHAR(20)
                );
                """;
        try{
            Connection c = getConnection();
            Statement st = c.createStatement();
            st.execute(ddl);
        } catch (SQLException e) {
            throw new RuntimeException("Error inicializando schema", e);
        }
    }

    @Override
    public Curso crearCurso(Curso curso) {
        if (curso == null) throw new IllegalArgumentException("El curso no puede ser null");
        String sql = "INSERT INTO cursos (activo, nombre) VALUES (?, ?)";
        try (Connection c = getConnection(); PreparedStatement ps = c.preparedStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setBoolean(1, curso.isActivo());
            ps.setString(2, curso.getNombre());
            ps.executeUpdate();
            ResultSet keys = ps.getGeneratedKeys();
            if (keys.next()) {
                curso.setId(keys.getInt(1));
            }
            return curso;
        }catch (SQLException e){
            throw new RuntimeException("Error insertando curso", e);
        }
        }

    @Override
    public Curso activar(Curso curso) {
        if (curso == null) throw new IllegalArgumentException("El curso no puede ser null");
        if (curso.getId() == null || curso.getId() <= 0){
            throw new IllegalArgumentException("El id debe de ser un entero positivo");
        }
        String sql = "UPDATE cursos SET activo=? WHERE activo=?";
        try{
            Connection c = getConnection();
            PreparedStatement ps = c.prepareStatement(sql);
            ps.setBoolean(1,Boolean.getBoolean("true"));
            int updated = ps.executeUpdate();
            if(updated == 1){
                throw new IllegalArgumentException("No existe curso con id " + curso.getId());
            }
            return curso;
        }
    }

    @Override
    public void eliminarSiNombreContiene(String texto) {

    }

    @Override
    public List<Curso> listarPorEstado(Boolean estado) {
        return List.of();
    }

    @Override
    public List<Curso> listarOrdenadoPor(String campo, String ordenacion) {
        return List.of();
    }
}
